name: CI

# 在master分支发生push事件时触发。
on: 
  push:
    branches:
      - master

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-18.04 #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps: # 步骤
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      
      - name: Deploy blog
        env: 
          # Coding 仓库
          CODING_REPO: ${{ secrets.CODING_REPO }}
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        # 将编译后的博客文件推送到指定仓库
        run: |
          npm install && npm run build
          cd docs/.vuepress/dist && git init
          git config user.name "$GIT_NAME"
          git config user.email "$GIT_EMAIL"
          git add -A
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet https://iENwpLnsTb:$CODING_TOKEN@$CODING_REPO master
          cd -
          rm -rf docs/.vuepress/dist